services:
  backend-dev:
    build:
      context: .
      dockerfile: Ecommerce/Dockerfile
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "mysql://root:password@db:3306/smart_app"
      NODE_ENV: development
      PORT: 5000
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: smart_app
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
